/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package romansnumbers;
import romansnumbers.Calculate.CalculateDecimalNumber;
import romansnumbers.EnumRomansNumbers.RomanNumbersValues;
import romansnumbers.RomansRegex.RomanNumbersRegexFilter;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
